server:
  port: 9000
spring:
  application:
    name: video-service
  zipkin:
    base-url: http://longsan:9411/
    discovery-client-enabled: false
  sleuth:
    sampler:
      probability: 1.0 # 采样的百分比
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://122.112.249.42:3307/cloud_video?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: longsan:8848
    sentinel:
      transport:
        dashboard: longsan:8080
        port: 8101 # 这个端口是用来此服务和sentinel（dashboard）通信使用的
#        clientIp: 182.148.4.116
# 控制台输出sql、下划线转驼峰
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true